# Generated by Django 4.0.5 on 2022-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('nroSeguimiento', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
                ('producto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cargoEntrega', models.IntegerField()),
                ('entregaRealizada', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('nroSeguimiento', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
                ('producto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'envio',
            },
        ),
    ]
